export const ADD_POST = "ADD_POST";

export const UPDATE_STICKY = "UPDATE_STICKY";

export const UPDATE_AUTHENTICATING = "UPDATE_AUTHENTICATING";
export const UPDATE_AUTHENTICATED = "UPDATE_AUTHENTICATED";
