export const ADD_POSTS = "ADD_POSTS";

export const UPDATE_STICKY = "UPDATE_STICKY";

export const UPDATE_AUTHENTICATING = "UPDATE_AUTHENTICATING";
export const UPDATE_AUTHENTICATED = "UPDATE_AUTHENTICATED";
